function repeatString(string, n, separator = " ") {
	if (n <= 0) {
		return "";
	}
	return Array(n).fill(string).join(separator);
}

function slugify(string) {
	return string
		.toLowerCase()
		.replace(/[^a-z0-9]/g, "-")
		.replace(/-+/g, "-")
		.replace(/^-|-$/g, "");
}

// This function was generated by ChatGPT
function parseCssToObject(cssString) {
	const cssObject = {};
	const regex = /([.#]?[a-zA-Z0-9_-]+)\s*\{([^}]+)\}/g;

	let match;
	while ((match = regex.exec(cssString)) !== null) {
		const selector = match[1].trim();
		const propertiesBlock = match[2].trim();

		const properties = {};
		propertiesBlock.split(";").forEach((line) => {
			const [key, value] = line.split(":").map((str) => str.trim());
			if (key && value) {
				properties[key] = value;
			}
		});

		cssObject[selector] = properties;
	}

	return cssObject;
}

module.exports = {
	repeatString,
	slugify,
	parseCssToObject
};
